//
//  Localizable.swift
//  DoroDoro
//
//  Created by Jinwoo Kim on 2/26/21.
//

import Foundation

internal enum Localizable: String {
    case DORODORO
    case TABBAR_SEARCH_VIEW_CONTROLLER_TITLE
    case TABBAR_BOOKMARKS_VIEW_CONTROLLER_TITLE
    case TABBAR_SETTINGS_VIEW_CONTROLLER_TITLE
    case MAP_VIEW_CONTROLLER_TITLE
    case DONE
    case DISMISS
    case NO_DATA
    case RESULTS_FOR_ADDRESS
    case ADD_TO_BOOKMARKS
    case REMOVE_FROM_BOOKMARKS
    case OPEN_IN_KAKAOMAP_APP
    case OPEN_IN_SYSTEM_MAPS_APP
    case COPY
    case SHARE
    case ERROR_CONTACT_TO_DEVELOPER
    case ADDR_LINK_API_ERROR_NORMAL
    case ADDR_LINK_API_ERROR_SYSTEM_ERROR
    case ADDR_LINK_API_ERROR_UNAUTHORIZED_API_KEY
    case ADDR_LINK_API_ERROR_EMPTY_KEYWORD
    case ADDR_LINK_API_ERROR_DEFICIENT_KEYWORD
    case ADDR_LINK_API_ERROR_TOO_SHORT_KEYWORD
    case ADDR_LINK_API_ERROR_WRONG_KEYWORD
    case ADDR_LINK_API_ERROR_TOO_LONG_KEYWORD
    case ADDR_LINK_API_ERROR_TOO_LONG_INTEGER_KEYWORD
    case ADDR_LINK_API_ERROR_KEYWORD_ONLY_CONTAINS_SPECIAL_CHARACTER
    case ADDR_LINK_API_ERROR_KEYWORD_COTAINS_SQL_RESERVED_CHARACTER
    case ADDR_LINK_API_ERROR_EXPIRED_KEY
    case ADDR_LINK_API_ERROR_TOO_MANY_RESULTS
    case ADDR_LINK_API_ERROR_RESPONSE
    case ADDR_LINK_API_ERROR_JSON_PARSE
    case ADDR_LINK_API_ERROR_NO_RESULTS
    case ADDR_LINK_API_ERROR_UNKNOWN
    case ADDR_ENG_API_ERROR_NORMAL
    case ADDR_ENG_API_ERROR_SYSTEM_ERROR
    case ADDR_ENG_API_ERROR_UNAUTHORIZED_API_KEY
    case ADDR_ENG_API_ERROR_EMPTY_KEYWORD
    case ADDR_ENG_API_ERROR_DEFICIENT_KEYWORD
    case ADDR_ENG_API_ERROR_TOO_SHORT_KEYWORD
    case ADDR_ENG_API_ERROR_WRONG_KEYWORD
    case ADDR_ENG_API_ERROR_TOO_LONG_KEYWORD
    case ADDR_ENG_API_ERROR_TOO_LONG_INTEGER_KEYWORD
    case ADDR_ENG_API_ERROR_KEYWORD_ONLY_CONTAINS_SPECIAL_CHARACTER
    case ADDR_ENG_API_ERROR_KEYWORD_COTAINS_SQL_RESERVED_CHARACTER
    case ADDR_ENG_API_ERROR_EXPIRED_KEY
    case ADDR_ENG_API_ERROR_TOO_MANY_RESULTS
    case ADDR_ENG_API_ERROR_RESPONSE
    case ADDR_ENG_API_ERROR_JSON_PARSE
    case ADDR_ENG_API_ERROR_NO_RESULTS
    case ADDR_ENG_API_ERROR_UNKNOWN
    case KAKAO_ADDRESS_API_ERROR_RESPONSE
    case KAKAO_ADDRESS_API_ERROR_JSON_PARSE
    case KAKAO_ADDRESS_API_ERROR_NO_RESULTS
    case KAKAO_ADDRESS_API_UNKNOWN
    
    internal var string: String {
        NSLocalizedString(self.rawValue, comment: "")
    }
}
